### ISSUE TITLE
Version number error somewhere in 0.5.2

### ISSUE THREAD

**Issue by fluffig** [janrieke/contractmanager#17]
Following error occurs after upgrading from 0.5.1 to 0.5.2 within Jameica 2.6.4:

```
[Mon Mar 13 15:31:28 CET 2017][ERROR][de.willuhn.jameica.services.ClassService.load] error while loading class de.janrieke.contractmanager.gui.parts.ExpensesAnalysisChartPart
java.lang.UnsupportedClassVersionError: de/janrieke/contractmanager/gui/parts/ExpensesAnalysisChartPart : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at de.willuhn.util.MultipleClassLoader.findVia(MultipleClassLoader.java:312)
        at de.willuhn.util.MultipleClassLoader.load(MultipleClassLoader.java:265)
        at de.willuhn.jameica.services.ClassService.load(ClassService.java:302)
        at de.willuhn.jameica.services.ClassService.prepareClasses(ClassService.java:274)
        at de.willuhn.jameica.services.ClassService.prepareClasses(ClassService.java:178)
        at de.willuhn.jameica.plugin.PluginLoader.loadPlugin(PluginLoader.java:318)
        at de.willuhn.jameica.plugin.PluginLoader.init(PluginLoader.java:217)
        at de.willuhn.jameica.services.PluginService.init(PluginService.java:42)
        at de.willuhn.boot.BootLoader.resolve(BootLoader.java:139)
        at de.willuhn.boot.BootLoader.resolve(BootLoader.java:119)
        at de.willuhn.boot.BootLoader.getBootable(BootLoader.java:72)
        at de.willuhn.jameica.system.Application.init(Application.java:106)
        at de.willuhn.jameica.system.Application.newInstance(Application.java:90)
        at de.willuhn.jameica.Main.main(Main.java:78)
```
Sadly I'm kind of stupid in doing java so I can't help any further.

**Comment by janrieke** [comment]
Java 7 is not supported any more. Use Java 8 instead (Jameica works fine with it).

**Comment by fluffig** [comment]
Thanks, just switched java version and everything works fine again!
Some hint after installation would be fine, in case other people run into this caveat too.

**Comment by janrieke** [comment]
I will update my blog post. However, there is no way of getting a message (or similar) to the user in Jameica before or after the installation.
