### ISSUE TITLE
0.5.3 NullPointer Exception bei "Verträge"

### ISSUE THREAD

**Issue by DanielRiek** [janrieke/contractmanager#19]
Nach dem Update auf 0.5.3 und öffnen vom Menüpunkt "Verträge".

Stacktrace:
```
java.lang.NullPointerException
	at java.util.Calendar.setTime(Unknown Source)
	at de.janrieke.contractmanager.util.DateUtils.calculateNextTermBeginAfter(DateUtils.java:70)
	at de.janrieke.contractmanager.server.ContractImpl.calculateNextTermBegin(ContractImpl.java:623)
	at de.janrieke.contractmanager.server.ContractImpl.calculateNextCancellationDeadline(ContractImpl.java:657)
	at de.janrieke.contractmanager.server.ContractImpl.getNextCancellationDeadline(ContractImpl.java:716)
	at de.janrieke.contractmanager.server.ContractImpl.isNextDeadlineWithin(ContractImpl.java:937)
	at de.janrieke.contractmanager.server.ContractImpl.isNextDeadlineWithinWarningTime(ContractImpl.java:928)
	at de.janrieke.contractmanager.gui.control.ContractControl.lambda$getContractsTable$6(ContractControl.java:749)
	at de.willuhn.jameica.gui.parts.TablePart.addItem(TablePart.java:526)
	at de.willuhn.jameica.gui.parts.TablePart.addItem(TablePart.java:382)
	at de.willuhn.jameica.gui.parts.TablePart.paint(TablePart.java:672)
	at de.janrieke.contractmanager.gui.view.ContractListView.bind(ContractListView.java:58)
	at de.willuhn.jameica.gui.GUI$5.run(GUI.java:699)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(Unknown Source)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:896)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Unknown Source)
	at org.eclipse.swt.widgets.Display.syncExec(Unknown Source)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:892)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:590)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:525)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:562)
	at de.janrieke.contractmanager.gui.action.ShowContractListView.handleAction(ShowContractListView.java:33)
	at de.willuhn.jameica.gui.Navigation.start(Navigation.java:385)
	at de.willuhn.jameica.gui.Navigation.access$500(Navigation.java:52)
	at de.willuhn.jameica.gui.Navigation$MyActionListener.handleEvent(Navigation.java:480)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:913)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:324)
	at de.willuhn.jameica.system.Application.init(Application.java:148)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:90)
	at de.willuhn.jameica.Main.main(Main.java:78)

```

**Comment by janrieke** [comment]
Mist. Wenn ich das richtig sehe, dann passiert das, wenn ein Vertrag kein Start- und Enddatum, aber trotzdem Laufzeiten hat. Den Fall hatte ich nicht auf dem Schirm.
Falls du irgendwie (z.B. über eine Hibiscus-Umsatz-Zuordnung) noch in die Vertragsdetails kommst, kannst du als Workaround ein Startdatum setzen oder die Laufzeiten rausnehmen. Ich versuche so schnell wie es geht ein Release zu machen mit dem Fix.

**Comment by janrieke** [comment]
Will be fixed in 0.5.4.

**Comment by janrieke** [comment]
0.5.4 ist raus.

**Comment by DanielRiek** [comment]
Danke, funktioniert!
