### ISSUE TITLE
Cannot install ContractManager 0.5.3

### ISSUE THREAD

**Issue by janrieke** [janrieke/contractmanager#20]
```
[ERROR][main][de.janrieke.contractmanager.ContractManagerPlugin.call] Unable to init db service
java.rmi.RemoteException: connection to database.jdbc:h2:C:\Users\USER\.jameica-fresh-install\contractmanager/h2db/contract_db;CIPHER=XTEA failed; nested exception is: 
	org.h2.jdbc.JdbcSQLException: Verschlüsselungsfehler in Datei null
Encryption error in file null [90049-193]
	at de.willuhn.datasource.db.DBServiceImpl.createConnection(DBServiceImpl.java:183)
	at de.willuhn.datasource.db.DBServiceImpl.getConnection(DBServiceImpl.java:126)
	at de.janrieke.contractmanager.server.ContractDBServiceImpl.getConnection(ContractDBServiceImpl.java:164)
	at de.janrieke.contractmanager.server.ContractDBServiceImpl.install(ContractDBServiceImpl.java:190)
	at de.janrieke.contractmanager.ContractManagerPlugin.lambda$install$1(ContractManagerPlugin.java:73)
	at de.janrieke.contractmanager.ContractManagerPlugin.call(ContractManagerPlugin.java:119)
	at de.janrieke.contractmanager.ContractManagerPlugin.install(ContractManagerPlugin.java:73)
	at de.willuhn.jameica.plugin.PluginLoader.initPlugin(PluginLoader.java:371)
	at de.willuhn.jameica.plugin.PluginLoader.init(PluginLoader.java:239)
	at de.willuhn.jameica.services.PluginService.init(PluginService.java:42)
	at de.willuhn.boot.BootLoader.resolve(BootLoader.java:139)
	at de.willuhn.boot.BootLoader.resolve(BootLoader.java:119)
	at de.willuhn.boot.BootLoader.getBootable(BootLoader.java:72)
	at de.willuhn.jameica.system.Application.init(Application.java:106)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:90)
	at de.willuhn.jameica.Main.main(Main.java:78)
```

**Comment by janrieke** [comment]
Happens occasionally on fresh installations. Unknown cause. Difficult to reproduce.
Completely uninstalling ContractManager (including user data) seems to fix the problem.
